server:
  port: 8095

spring:
  application:
    name: interfaz-usuarios-sibex

  datasource:
    url: jdbc:postgresql://localhost:5432/marvel
    driverClassName: org.postgresql.Driver
    platform: org.hibernate.dialect.PostgreSQLDialect
    username: postgres
    password: postgres

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
